# These are supported funding model platforms

github: [ciriarte]
patreon: ciriarte
open_collective: # Replace with a single Open Collective username
ko_fi: ciriarte
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL